#!/usr/bin/env guile
!#

;; (add-to-load-path (dirname (current-filename)))
 
(use-modules (ice-9 match)
	     (ice-9 getopt-long)
	     (srfi srfi-1)
	     (zeta-lib cmds)
	     (zeta-lib term))

(define option-spec
  '((manifest (single-char #\m) (value #t))))

(define options (getopt-long (command-line) option-spec))

(define provided-manifest (option-ref options 'manifest #f))

(define cmdline (command-line))

(when provided-manifest
  (set! cmdline 
	(remove (lambda (str)
		  (or (string-contains str "--manifest")
		      (string= str "-m"))) cmdline))
  (set! cmdline (delete provided-manifest cmdline)))

;; (println provided-manifest)
;; (println cmdline)
;; (exit)

(match cmdline
  ;; TODO 
  ;; ((_ "init")		(zeta-init)) 
  ;; ((_ "init" init-location)	(zeta-init init-location))
  ((_ "add" manifest-path ...)	(zeta-add manifest-path))
  ((_ "del" manifest-path ...)	(zeta-del manifest-path))
  ((_ "install" pkgs ...)	(zeta-install pkgs provided-manifest))
  ((_  "remove" pkgs ...)	(zeta-remove pkgs provided-manifest))
  ((_ "init")			(zeta-init))
  ((_ "list")			(zeta-list))
  (_ (usage)))
